name: mine_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  sizer: ^2.0.15
  curved_navigation_bar: ^1.0.3
  hive: ^2.2.3
  get_it: ^7.6.4
  intl: ^0.19.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  sqflite: ^2.3.0
  test: ^1.24.9
  animated_text_kit: ^4.2.2
  dartz: ^0.10.1
  uuid: ^4.2.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
